language: go
go_import_path: github.com/grokify/html-strip-tags-go
go:
  - "1.12.x"
  - "1.11.x"
  - "1.10.x"
  - "1.9.x"
  - "1.8.x"
  - "1.7.x"
  - "1.6.x"
  - "1.5.x"
  - "1.4.x"
  - "1.3.x"
  - "1.2.x"
  - "1.1.x"
  - "1.0.x"
  - tip
matrix:
  allow_failures:
    - go: tip
sudo: true 
install:
  - go get -t -v ./...
script:
  - go test -v ./...
 